# Generated by Django 3.1.1 on 2020-09-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_etebase", "0029_auto_20200907_0801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="main_item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="django_etebase.collectionitem",
            ),
        ),
    ]
