# Generated by Django 3.1.1 on 2020-10-13 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_etebase", "0030_auto_20200922_0832"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.BinaryField(db_index=True, editable=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="collectionmember",
            name="collectionType",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="django_etebase.collectiontype"
            ),
        ),
    ]
