# Generated by Django 3.1.1 on 2020-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_etebase", "0031_auto_20201013_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiontype",
            name="uid",
            field=models.BinaryField(db_index=True, editable=True, max_length=1024, unique=True),
        ),
    ]
