# Generated by Django 3.0.3 on 2020-02-20 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemchunk',
            name='itemSnapshot',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='hmac',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionitemchunk',
            name='items',
            field=models.ManyToManyField(related_name='chunks', to='django_etesync.CollectionItem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, validators=[django.core.validators.RegexValidator(message='Not a valid UID. Expected a 256bit base64url.', regex='[a-zA-Z0-9\\-_=]{44}')]),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_etesync.Collection'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, validators=[django.core.validators.RegexValidator(message='Not a valid UID. Expected a 256bit base64url.', regex='[a-zA-Z0-9\\-_=]{44}')]),
        ),
        migrations.AlterField(
            model_name='collectionitemchunk',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, validators=[django.core.validators.RegexValidator(message='Not a valid UID. Expected a 256bit base64url.', regex='[a-zA-Z0-9\\-_=]{44}')]),
        ),
        migrations.DeleteModel(
            name='CollectionItemSnapshot',
        ),
    ]
