# Generated by Django 3.0.3 on 2020-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0002_auto_20200220_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
