# Generated by Django 3.0.3 on 2020-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0003_collectioninvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninvitation',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
