# Generated by Django 3.0.3 on 2020-02-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0004_auto_20200220_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemchunk',
            name='items',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='chunks',
            field=models.ManyToManyField(related_name='items', to='django_etesync.CollectionItemChunk'),
        ),
        migrations.AddField(
            model_name='collectionitemchunk',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='django_etesync.Collection'),
            preserve_default=False,
        ),
    ]
