# Generated by Django 3.0.3 on 2020-02-20 12:16

from django.db import migrations, models
import django_etesync.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0007_auto_20200220_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitemchunk',
            name='chunkFile',
            field=models.FileField(default='', upload_to=django_etesync.models.chunk_directory_path),
            preserve_default=False,
        ),
    ]
