# Generated by Django 3.0.3 on 2020-02-20 12:48

from django.db import migrations, models
import django_etesync.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0009_auto_20200220_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemchunk',
            name='chunkFile',
            field=models.FileField(max_length=150, unique=True, upload_to=django_etesync.models.chunk_directory_path),
        ),
    ]
