# Generated by Django 3.0.3 on 2020-02-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0010_auto_20200220_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionItemSnapshot',
            new_name='CollectionItemRevision',
        ),
    ]
