# Generated by Django 3.0.3 on 2020-02-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0011_auto_20200220_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='django_etesync.CollectionItem'),
        ),
    ]
