# Generated by Django 3.0.3 on 2020-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0012_auto_20200220_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitemrevision',
            name='is_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
