# Generated by Django 3.0.3 on 2020-02-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0013_collectionitemrevision_is_deletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitemrevision',
            old_name='is_deletion',
            new_name='isDeletion',
        ),
    ]
