# Generated by Django 3.0.3 on 2020-02-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0014_auto_20200226_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='current',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
    ]
