# Generated by Django 3.0.3 on 2020-02-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0016_auto_20200226_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitemrevision',
            old_name='isDeletion',
            new_name='deleted',
        ),
    ]
