# Generated by Django 3.0.3 on 2020-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0017_auto_20200226_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='current',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
    ]
