# Generated by Django 3.0.3 on 2020-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0021_auto_20200310_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemrevision',
            name='encryptionKey',
        ),
        migrations.RemoveField(
            model_name='collectionitemrevision',
            name='version',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='encryptionKey',
            field=models.BinaryField(default=b'aoesnutheounth', editable=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
