# Generated by Django 3.0.3 on 2020-03-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0022_auto_20200310_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitemchunk',
            options={'ordering': ('item', 'order')},
        ),
    ]
