# Generated by Django 3.0.3 on 2020-03-12 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0023_auto_20200310_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitemrevision',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, validators=[django.core.validators.RegexValidator(message='Not a valid UID', regex='[a-zA-Z0-9]')]),
        ),
    ]
