# Generated by Django 3.0.3 on 2020-03-12 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0024_collectionitemrevision_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, unique=True, validators=[django.core.validators.RegexValidator(message='Not a valid UID', regex='[a-zA-Z0-9]')]),
        ),
    ]
