# Generated by Django 3.0.3 on 2020-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0025_auto_20200312_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitemrevision',
            name='meta',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
