# Generated by Django 3.0.3 on 2020-03-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0026_collectionitemrevision_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mainItem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of_collection', to='django_etesync.CollectionItem'),
        ),
    ]
