# Generated by Django 3.0.3 on 2020-03-12 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0027_collection_mainitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='encryptionKey',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid UID', regex='[a-zA-Z0-9]')]),
        ),
    ]
