# Generated by Django 3.0.3 on 2020-03-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0029_auto_20200312_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mainItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='of_collection', to='django_etesync.CollectionItem'),
        ),
    ]
