# Generated by Django 3.0.3 on 2020-03-17 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0030_auto_20200312_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemchunk',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, validators=[django.core.validators.RegexValidator(message='Expected a 256bit base64url.', regex='^[a-zA-Z0-9\\-_]{43}$')]),
        ),
    ]
