# Generated by Django 3.0.3 on 2020-03-17 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0031_auto_20200317_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemrevision',
            name='hmac',
        ),
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='uid',
            field=models.CharField(db_index=True, max_length=44, unique=True, validators=[django.core.validators.RegexValidator(message='Expected a 256bit base64url.', regex='^[a-zA-Z0-9\\-_]{43}$')]),
        ),
    ]
