# Generated by Django 3.0.3 on 2020-03-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0032_auto_20200317_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemrevision',
            name='meta',
            field=models.BinaryField(default=b'', editable=True),
            preserve_default=False,
        ),
    ]
