# Generated by Django 3.0.3 on 2020-04-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0034_auto_20200415_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mainItem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_collection', to='django_etesync.CollectionItem'),
        ),
    ]
