# Generated by Django 3.0.3 on 2020-04-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0035_auto_20200415_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitemchunk',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='collectionitemchunk',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RevisionChunkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions_relation', to='django_etesync.CollectionItemChunk')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks_relation', to='django_etesync.CollectionItemRevision')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='collectionitemchunk',
            name='order',
        ),
    ]
