# Generated by Django 3.0.3 on 2020-04-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etesync', '0037_auto_20200415_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemrevision',
            name='chunks',
        ),
    ]
