# Generated by Django 3.0.3 on 2020-05-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_etebase", "0009_auto_20200526_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitemrevision",
            name="stoken",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="django_etebase.Stoken"),
        ),
    ]
