# Generated by Django 3.0.3 on 2020-05-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0010_auto_20200526_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmember',
            name='stoken',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_etebase.Stoken'),
        ),
    ]
