# Generated by Django 3.0.3 on 2020-05-27 07:43

from django.db import migrations


def create_stokens(apps, schema_editor):
    Stoken = apps.get_model('django_etebase', 'Stoken')
    CollectionMember = apps.get_model('django_etebase', 'CollectionMember')

    for member in CollectionMember.objects.all():
        member.stoken = Stoken.objects.create()
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0011_collectionmember_stoken'),
    ]

    operations = [
        migrations.RunPython(create_stokens),
    ]
