# Generated by Django 3.0.3 on 2020-05-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_etebase", "0012_auto_20200527_0743"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionMemberRemoved",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removed_members",
                        to="django_etebase.Collection",
                    ),
                ),
                (
                    "stoken",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="django_etebase.Stoken"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("user", "collection")},},
        ),
    ]
