# Generated by Django 3.0.3 on 2020-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0014_auto_20200602_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitemrevision',
            name='salt',
            field=models.BinaryField(default=b'', editable=True),
        ),
    ]
