# Generated by Django 3.0.3 on 2020-06-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0019_auto_20200626_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemrevision',
            name='salt',
        ),
    ]
