# Generated by Django 3.0.3 on 2020-08-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_etebase", "0022_auto_20200804_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitemchunk",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="django_etebase.Collection",
            ),
        ),
    ]
