# Generated by Django 3.1.1 on 2020-12-14 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0032_auto_20201013_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uid',
            field=models.CharField(db_index=True, max_length=43, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid UID', regex='^[a-zA-Z0-9\\-_]{20,}$')]),
        ),
    ]
