# Generated by Django 3.1.1 on 2020-12-24 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_etebase', '0036_auto_20201214_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=43, unique=True, validators=[django.core.validators.RegexValidator(message='Not a valid UID', regex='^[a-zA-Z0-9\\-_]{20,}$')])),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('content', models.BinaryField()),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_simple_messages', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_simple_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
