# Generated by Django 3.0.3 on 2020-05-15 08:01

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[myauth.models.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
